# -*- coding: utf-8 -*-
"""AddestramentoModello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl8FQ6HQkf2lqHLnqhXWhHGevHgMLCp3
"""

from google.colab import drive
drive.mount('/content/drive')

#Versione con dati in chiaro

import os
#Libreire PyTorch per le reti neurali
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms #trasformazione immagini
from torch.utils.data import Dataset, DataLoader, Subset #gestione dei dati
from torch.optim.lr_scheduler import OneCycleLR
#Manipolazione dati
import numpy as np
import pandas as pd
#processing delle immagini
from PIL import Image
#metriche e preprocessing
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, recall_score, precision_score
#bilanciamento classi
from imblearn.over_sampling import SMOTE
#visualizzazione grafica
import matplotlib.pyplot as plt
import seaborn as sns

# Configurazione device e seed
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(42)
np.random.seed(42)
torch.backends.cudnn.deterministic = True

#numero di epoche
epcs = 40

# Definizione del Dataset
class HybridMRIDataset(Dataset):
  #caricamento immagini (MRI) e informazioni dal CSV
    def __init__(self, img_folder, csv_path, transform=None):
        self.img_folder = img_folder
        self.csv_path = csv_path
        self.transform = transform
        self.samples = []

        # #creazione dataframe
        self.df = pd.read_csv(csv_path)
        self.df['EDSS'] = self.df['EDSS'].astype(str).str.replace(',', '.').astype(float)

        #selezione delle feature tabulari (quelle più influenti per il calcolo dell'EDSS)
        self.tabular_features = ['Pyramidal', 'Coordination', 'Motor_System', 'Visual', 'Gait', 'Age']
        self.scaler = StandardScaler()
        self.df[self.tabular_features] = self.scaler.fit_transform(self.df[self.tabular_features])

        def edss_to_label(edss):
            if edss <= 1.5: return 0
            elif edss <= 3.0: return 1
            else: return 2

        # raccolta campioni originali
        temp_samples = []
        for file in os.listdir(img_folder):
            if file.endswith(".png"):
                try:
                  #estrazione id del paziente dall'immagine
                    patient_id = int(file.split("_")[0])
                    #estrazione dati tramite ID
                    patient_data = self.df[self.df['ID'] == patient_id]

                    #gestione EDSS
                    if not patient_data.empty:
                        if "_EDSS" in file:
                            edss_str = file.split("_EDSS")[-1].replace(".png", "").replace(",", ".")
                            edss = float(edss_str)
                        else:
                            edss = patient_data['EDSS'].values[0]

                        label = edss_to_label(edss)
                        tabular_data = patient_data[self.tabular_features].values[0]
                        temp_samples.append((file, tabular_data, label))
                except Exception as e:
                    print(f"Errore processando {file}: {str(e)}")
                    continue

        # Distribuzione classi originale
        class_counts = np.bincount([label for _, _, label in temp_samples])
        print("-" * 50)
        print("\nDistribuzione classi originale:")
        for cls, count in enumerate(class_counts):
            print(f"Classe {cls}: {count} campioni")

        max_count = max(class_counts)
        balanced_samples = []

        #bilanciamento dei sample
        for cls in range(3):
            cls_samples = [s for s in temp_samples if s[2] == cls]
            # Ripetizione ciclica dei campioni
            repeat_times = max_count // len(cls_samples)
            remainder = max_count % len(cls_samples)
            cls_samples = cls_samples * repeat_times + cls_samples[:remainder]
            balanced_samples.extend(cls_samples)

        # Creazione dataset bilanciato
        for file, tabular, label in balanced_samples:
            self.samples.append((
                os.path.join(img_folder, file),
                tabular,
                label
            ))

        # Verifica bilanciamento
        print("-" * 50)
        print("\nDistribuzione classi bilanciata:")
        unique, counts = np.unique([label for _, _, label in self.samples], return_counts=True)
        for cls, count in zip(unique, counts):
            print(f"Classe {cls}: {count} campioni")

    #restituzione numero totale dei campioni
    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, tabular_data, label = self.samples[idx] #recupero dati
        img = Image.open(img_path).convert("L") #caricamento immagine e conversione in scala di grigi
        if self.transform: #trasformazione
            img = self.transform(img)
        return img, torch.tensor(tabular_data, dtype=torch.float32), torch.tensor(label, dtype=torch.long) #output in formato tensore

# Data Augmentation
train_transform = transforms.Compose([
    transforms.Resize((128, 128)), #ridimensionamento
    transforms.RandomAffine(degrees=15, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 0.5)), #sfocatura
    transforms.RandomPerspective(distortion_scale=0.2, p=0.3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
    transforms.RandomErasing(p=0.3, scale=(0.02, 0.1), ratio=(0.3, 3.3))
])

test_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# Modello
class EnhancedCrossModalityAttention(nn.Module):
    def __init__(self, img_feat_dim, tab_feat_dim):
        super().__init__()
        self.img_proj = nn.Sequential(
            nn.Linear(img_feat_dim, img_feat_dim),
            nn.BatchNorm1d(img_feat_dim),
            nn.LeakyReLU(0.1)
        )
        self.tab_proj = nn.Sequential(
            nn.Linear(tab_feat_dim, img_feat_dim),
            nn.BatchNorm1d(img_feat_dim),
            nn.LeakyReLU(0.1)
        )
        self.attention = nn.Sequential(
            nn.Linear(img_feat_dim * 2, img_feat_dim),
            nn.LeakyReLU(0.1),
            nn.Linear(img_feat_dim, img_feat_dim),
            nn.Sigmoid()
        )

    def forward(self, img_features, tab_features):
        img_proj = self.img_proj(img_features)
        tab_proj = self.tab_proj(tab_features)
        combined = torch.cat([img_proj, tab_proj], dim=1)
        attention_weights = self.attention(combined)
        return attention_weights * img_proj + (1 - attention_weights) * tab_proj

#classe per classificatore ibrido
class EnhancedHybridEDSSClassifier(nn.Module):
    def __init__(self, num_tabular_features=6, num_classes=3):
        super().__init__()

        # Branch immagini con maggiore regolarizzazione
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), # 1° strato convoluzionale
            nn.BatchNorm2d(32), #normalizzazione
            nn.LeakyReLU(0.1), #attivazione
            nn.MaxPool2d(2), #downsampling
            nn.Dropout(0.3), #regolarizzazione

            nn.Conv2d(32, 64, 3, padding=1), # 2° strato convoluzionale
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.1),
            nn.MaxPool2d(2),
            nn.Dropout(0.4),

            nn.Conv2d(64, 128, 3, padding=1), # 3° strato convoluzionale
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.1),
            nn.AdaptiveAvgPool2d((8, 8)), #pooling adattivo
            nn.Dropout(0.5)
        )

        # Branch tabellare
        self.tab_fc = nn.Sequential(
            nn.Linear(num_tabular_features, 64), # 1° strato convoluzionale
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.4),

            nn.Linear(64, 128), # 2° strato convoluzionale
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.5)
        )

        self.attention = EnhancedCrossModalityAttention(img_feat_dim=128*8*8, tab_feat_dim=128)

        # Classificatore con maggiore regolarizzazione
        self.classifier = nn.Sequential(
            nn.Linear(128*8*8, 256), #riduzione dimensionale
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.6), #regolarizzazione
            nn.Linear(256, num_classes) #output
        )

        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='leaky_relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, img, tab_data):
        img_features = self.cnn(img).view(img.size(0), -1) #estrazione e appiattimento features immagine
        tab_features = self.tab_fc(tab_data) #elaborazione dati tabellari
        fused_features = self.attention(img_features, tab_features) #fusione
        return self.classifier(fused_features) #classificazione finale

class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2, reduction='mean'):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = (1 - pt)**self.gamma * ce_loss

        if self.alpha is not None:
            focal_loss = self.alpha[targets] * focal_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        return focal_loss

# Caricamento dati
img_folder = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices"
csv_path = "/content/drive/Shareddrives/ProgettoBigData/Patient_Info.csv"

dataset = HybridMRIDataset(img_folder, csv_path, transform=train_transform)

# Split stratificato
labels = np.array([label for _, _, label in dataset.samples])
train_idx, val_idx, test_idx = [], [], []

for class_id in [0, 1, 2]:
    class_indices = np.where(labels == class_id)[0]
    np.random.shuffle(class_indices)
    split1 = int(0.6 * len(class_indices))
    split2 = int(0.8 * len(class_indices))
    train_idx.extend(class_indices[:split1])
    val_idx.extend(class_indices[split1:split2])
    test_idx.extend(class_indices[split2:])

print("-" *50)
print(f"Train: {np.bincount([dataset[i][2] for i in train_idx])}")
print(f"Val: {np.bincount([dataset[i][2] for i in val_idx])}")
print(f"Test: {np.bincount([dataset[i][2] for i in test_idx])}")

train_set = Subset(dataset, train_idx)
val_set = Subset(dataset, val_idx)
test_set = Subset(dataset, test_idx)

# Creazione dei DataLoader
train_loader = DataLoader(train_set, batch_size=32, shuffle=True, pin_memory=True, num_workers=2)
val_loader = DataLoader(val_set, batch_size=32, pin_memory=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=32, pin_memory=True, num_workers=2)

# Inizializzazione modello
model = EnhancedHybridEDSSClassifier(num_classes=3).to(device)

# Ottimizzatore e scheduler
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
scheduler = OneCycleLR(optimizer, max_lr=1e-3, steps_per_epoch=len(train_loader), epochs=epcs)

# Focal Loss con pesi delle classi
class_weights = torch.tensor([0.9, 0.7, 1.5], device=device)
criterion = FocalLoss(alpha=class_weights, gamma=2.5)

scaler = torch.amp.GradScaler()

# Addestramento con early stopping
history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
best_val_acc = 0
patience = 5
patience_counter = 0

for epoch in range(epcs):
    model.train()
    train_loss, train_correct = 0, 0

    for images, tabular, labels in train_loader:
        images, tabular, labels = images.to(device), tabular.to(device), labels.to(device)

        optimizer.zero_grad()

        with torch.amp.autocast(device_type='cuda', dtype=torch.float16):
            outputs = model(images, tabular)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        train_correct += (predicted == labels).sum().item()

    # Validazione
    model.eval()
    val_loss, val_correct = 0, 0
    with torch.no_grad():
        for images, tabular, labels in val_loader:
            images, tabular, labels = images.to(device), tabular.to(device), labels.to(device)
            outputs = model(images, tabular)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            val_correct += (predicted == labels).sum().item()

    # Calcolo metriche
    train_loss /= len(train_loader)
    train_acc = train_correct / len(train_set)
    val_loss /= len(val_loader)
    val_acc = val_correct / len(val_set)

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print("-" * 50)
    print(f"Epoch [{epoch+1}/{epcs}]")
    print(f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")
    print(f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")

    # Early stopping
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        patience_counter = 0
        torch.save(model.state_dict(), 'best_model.pth')
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print("Early stopping triggered")
            break

# Caricamento miglior modello
model.load_state_dict(torch.load('best_model.pth'))

# Valutazione su Test
model.eval()
test_labels, test_preds, test_probs = [], [], []
with torch.no_grad():
    for images, tabular, labels in test_loader:
        images, tabular = images.to(device), tabular.to(device)
        outputs = model(images, tabular)
        probs = F.softmax(outputs, dim=1)
        _, preds = torch.max(outputs, 1)
        test_labels.extend(labels.cpu().numpy())
        test_preds.extend(preds.cpu().numpy())
        test_probs.extend(probs.cpu().numpy())

print("\nTest Classification Report:")
print(classification_report(test_labels, test_preds, digits=4))

# Matrice di confusione
cm = confusion_matrix(test_labels, test_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=[f'Class {i}' for i in range(3)],
            yticklabels=[f'Class {i}' for i in range(3)], cmap='Blues')
plt.title('Test Confusion Matrix')
plt.show()

print("\nMetriche Estese per Classe:")
# Calcolo sensibilità (recall) e precision
sensitivity = recall_score(test_labels, test_preds, average=None)
precision = precision_score(test_labels, test_preds, average=None)

# Calcolo specificità
def calculate_specificity(cm):
    specificity = []
    for i in range(cm.shape[0]):
        tn = np.sum(np.delete(np.delete(cm, i, axis=0), i, axis=1))
        fp = np.sum(cm[:, i]) - cm[i, i]
        specificity.append(tn / (tn + fp))
    return specificity

specificity = calculate_specificity(cm)

# Stampa risultati
for i in range(3):
    print(f"Classe {i}:")
    print(f"  - Recall: {sensitivity[i]:.4f}")
    print(f"  - Precision: {precision[i]:.4f}")
    print(f"  - Specificity: {specificity[i]:.4f}")
    print(f"  - F1-score: {2 * (precision[i] * sensitivity[i]) / (precision[i] + sensitivity[i]):.4f}")

# ROC Curve
plt.figure(figsize=(8,6))
y_test_bin = label_binarize(test_labels, classes=[0,1,2])
for i in range(3):
    fpr, tpr, _ = roc_curve(y_test_bin[:,i], np.array(test_probs)[:,i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Test ROC Curves')
plt.legend()
plt.show()

# Learning curves
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Train Loss')
plt.plot(history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Train Accuracy')
plt.plot(history['val_acc'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.tight_layout()
plt.show()

#Versione con dati decifrati

import os
#Libreire PyTorch per le reti neurali
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms #trasformazione immagini
from torch.utils.data import Dataset, DataLoader, Subset #gestione dei dati
from torch.optim.lr_scheduler import OneCycleLR
#Manipolazione dati
import numpy as np
import pandas as pd
#processing delle immagini
from PIL import Image
#metriche e preprocessing
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, recall_score, precision_score
#bilanciamento classi
from imblearn.over_sampling import SMOTE
#visualizzazione grafica
import matplotlib.pyplot as plt
import seaborn as sns
#cifratura dei risultati
!pip install pandas pycryptodome
import base64
import json
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Protocol.KDF import PBKDF2
import getpass
import signal
import sys

# Configurazione device e seed
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(42)
np.random.seed(42)
torch.backends.cudnn.deterministic = True

#numero di epoche
epcs = 40

# Definizione del Dataset
class HybridMRIDataset(Dataset):
  #caricamento immagini (MRI) e informazioni dal CSV
    def __init__(self, img_folder, csv_path, transform=None):
        self.img_folder = img_folder
        self.csv_path = csv_path
        self.transform = transform
        self.samples = []

        # #creazione dataframe
        self.df = pd.read_csv(csv_path)
        self.df['EDSS'] = self.df['EDSS'].astype(str).str.replace(',', '.').astype(float)

        #selezione delle feature tabulari (quelle più influenti per il calcolo dell'EDSS)
        self.tabular_features = ['Pyramidal', 'Coordination', 'Motor_System', 'Visual', 'Gait', 'Age']
        self.scaler = StandardScaler()
        self.df[self.tabular_features] = self.scaler.fit_transform(self.df[self.tabular_features])

        def edss_to_label(edss):
            if edss <= 1.5: return 0
            elif edss <= 3.0: return 1
            else: return 2

        # raccolta campioni originali
        temp_samples = []
        for file in os.listdir(img_folder):
            if file.endswith(".png"):
                try:
                  #estrazione id del paziente dall'immagine
                    patient_id = int(file.split("_")[0])
                    #estrazione dati tramite ID
                    patient_data = self.df[self.df['ID'] == patient_id]

                    #gestione EDSS
                    if not patient_data.empty:
                        if "_EDSS" in file:
                            edss_str = file.split("_EDSS")[-1].replace(".png", "").replace(",", ".")
                            edss = float(edss_str)
                        else:
                            edss = patient_data['EDSS'].values[0]

                        label = edss_to_label(edss)
                        tabular_data = patient_data[self.tabular_features].values[0]
                        temp_samples.append((file, tabular_data, label))
                except Exception as e:
                    print(f"Errore processando {file}: {str(e)}")
                    continue

        # Distribuzione classi originale
        class_counts = np.bincount([label for _, _, label in temp_samples])
        print("-" * 50)
        print("\nDistribuzione classi originale:")
        for cls, count in enumerate(class_counts):
            print(f"Classe {cls}: {count} campioni")

        max_count = max(class_counts)
        balanced_samples = []

        #bilanciamento dei sample
        for cls in range(3):
            cls_samples = [s for s in temp_samples if s[2] == cls]
            # Ripetizione ciclica dei campioni
            repeat_times = max_count // len(cls_samples)
            remainder = max_count % len(cls_samples)
            cls_samples = cls_samples * repeat_times + cls_samples[:remainder]
            balanced_samples.extend(cls_samples)

        # Creazione dataset bilanciato
        for file, tabular, label in balanced_samples:
            self.samples.append((
                os.path.join(img_folder, file),
                tabular,
                label
            ))

        # Verifica bilanciamento
        print("-" * 50)
        print("\nDistribuzione classi bilanciata:")
        unique, counts = np.unique([label for _, _, label in self.samples], return_counts=True)
        for cls, count in zip(unique, counts):
            print(f"Classe {cls}: {count} campioni")

    #restituzione numero totale dei campioni
    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, tabular_data, label = self.samples[idx] #recupero dati
        img = Image.open(img_path).convert("L") #caricamento immagine e conversione in scala di grigi
        if self.transform: #trasformazione
            img = self.transform(img)
        return img, torch.tensor(tabular_data, dtype=torch.float32), torch.tensor(label, dtype=torch.long) #output in formato tensore

# Data Augmentation
train_transform = transforms.Compose([
    transforms.Resize((128, 128)), #ridimensionamento
    transforms.RandomAffine(degrees=15, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 0.5)), #sfocatura
    transforms.RandomPerspective(distortion_scale=0.2, p=0.3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
    transforms.RandomErasing(p=0.3, scale=(0.02, 0.1), ratio=(0.3, 3.3))
])

test_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# Modello
class EnhancedCrossModalityAttention(nn.Module):
    def __init__(self, img_feat_dim, tab_feat_dim):
        super().__init__()
        self.img_proj = nn.Sequential(
            nn.Linear(img_feat_dim, img_feat_dim),
            nn.BatchNorm1d(img_feat_dim),
            nn.LeakyReLU(0.1)
        )
        self.tab_proj = nn.Sequential(
            nn.Linear(tab_feat_dim, img_feat_dim),
            nn.BatchNorm1d(img_feat_dim),
            nn.LeakyReLU(0.1)
        )
        self.attention = nn.Sequential(
            nn.Linear(img_feat_dim * 2, img_feat_dim),
            nn.LeakyReLU(0.1),
            nn.Linear(img_feat_dim, img_feat_dim),
            nn.Sigmoid()
        )

    def forward(self, img_features, tab_features):
        img_proj = self.img_proj(img_features)
        tab_proj = self.tab_proj(tab_features)
        combined = torch.cat([img_proj, tab_proj], dim=1)
        attention_weights = self.attention(combined)
        return attention_weights * img_proj + (1 - attention_weights) * tab_proj

#classe per classificatore ibrido
class EnhancedHybridEDSSClassifier(nn.Module):
    def __init__(self, num_tabular_features=6, num_classes=3):
        super().__init__()

        # Branch immagini con maggiore regolarizzazione
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), # 1° strato convoluzionale
            nn.BatchNorm2d(32), #normalizzazione
            nn.LeakyReLU(0.1), #attivazione
            nn.MaxPool2d(2), #downsampling
            nn.Dropout(0.3), #regolarizzazione

            nn.Conv2d(32, 64, 3, padding=1), # 2° strato convoluzionale
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.1),
            nn.MaxPool2d(2),
            nn.Dropout(0.4),

            nn.Conv2d(64, 128, 3, padding=1), # 3° strato convoluzionale
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.1),
            nn.AdaptiveAvgPool2d((8, 8)), #pooling adattivo
            nn.Dropout(0.5)
        )

        # Branch tabellare
        self.tab_fc = nn.Sequential(
            nn.Linear(num_tabular_features, 64), # 1° strato convoluzionale
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.4),

            nn.Linear(64, 128), # 2° strato convoluzionale
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.5)
        )

        self.attention = EnhancedCrossModalityAttention(img_feat_dim=128*8*8, tab_feat_dim=128)

        # Classificatore con maggiore regolarizzazione
        self.classifier = nn.Sequential(
            nn.Linear(128*8*8, 256), #riduzione dimensionale
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.6), #regolarizzazione
            nn.Linear(256, num_classes) #output
        )

        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='leaky_relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, img, tab_data):
        img_features = self.cnn(img).view(img.size(0), -1) #estrazione e appiattimento features immagine
        tab_features = self.tab_fc(tab_data) #elaborazione dati tabellari
        fused_features = self.attention(img_features, tab_features) #fusione
        return self.classifier(fused_features) #classificazione finale

class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2, reduction='mean'):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = (1 - pt)**self.gamma * ce_loss

        if self.alpha is not None:
            focal_loss = self.alpha[targets] * focal_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        return focal_loss

# Caricamento dati
img_folder = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices_decrypted"
csv_path = "/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Decrypted.csv"

dataset = HybridMRIDataset(img_folder, csv_path, transform=train_transform)

# Split stratificato
labels = np.array([label for _, _, label in dataset.samples])
train_idx, val_idx, test_idx = [], [], []

for class_id in [0, 1, 2]:
    class_indices = np.where(labels == class_id)[0]
    np.random.shuffle(class_indices)
    split1 = int(0.6 * len(class_indices))
    split2 = int(0.8 * len(class_indices))
    train_idx.extend(class_indices[:split1])
    val_idx.extend(class_indices[split1:split2])
    test_idx.extend(class_indices[split2:])

print("-" *50)
print(f"Train: {np.bincount([dataset[i][2] for i in train_idx])}")
print(f"Val: {np.bincount([dataset[i][2] for i in val_idx])}")
print(f"Test: {np.bincount([dataset[i][2] for i in test_idx])}")

train_set = Subset(dataset, train_idx)
val_set = Subset(dataset, val_idx)
test_set = Subset(dataset, test_idx)

# Creazione dei DataLoader
train_loader = DataLoader(train_set, batch_size=32, shuffle=True, pin_memory=True, num_workers=2)
val_loader = DataLoader(val_set, batch_size=32, pin_memory=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=32, pin_memory=True, num_workers=2)

# Inizializzazione modello
model = EnhancedHybridEDSSClassifier(num_classes=3).to(device)

# Ottimizzatore e scheduler
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-3)
scheduler = OneCycleLR(optimizer, max_lr=1e-3, steps_per_epoch=len(train_loader), epochs=epcs)

# Focal Loss con pesi delle classi
class_weights = torch.tensor([0.9, 0.7, 1.5], device=device)
criterion = FocalLoss(alpha=class_weights, gamma=2.5)

scaler = torch.amp.GradScaler()

# Addestramento con early stopping
history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
best_val_acc = 0
patience = 5
patience_counter = 0

try:

  for epoch in range(epcs):
      model.train()
      train_loss, train_correct = 0, 0

      for images, tabular, labels in train_loader:
          images, tabular, labels = images.to(device), tabular.to(device), labels.to(device)

          optimizer.zero_grad()

          with torch.amp.autocast(device_type='cuda', dtype=torch.float16):
              outputs = model(images, tabular)
              loss = criterion(outputs, labels)

          scaler.scale(loss).backward()
          scaler.step(optimizer)
          scaler.update()
          scheduler.step()

          train_loss += loss.item()
          _, predicted = torch.max(outputs.data, 1)
          train_correct += (predicted == labels).sum().item()

      # Validazione
      model.eval()
      val_loss, val_correct = 0, 0
      with torch.no_grad():
          for images, tabular, labels in val_loader:
              images, tabular, labels = images.to(device), tabular.to(device), labels.to(device)
              outputs = model(images, tabular)
              loss = criterion(outputs, labels)

              val_loss += loss.item()
              _, predicted = torch.max(outputs.data, 1)
              val_correct += (predicted == labels).sum().item()

      # Calcolo metriche
      train_loss /= len(train_loader)
      train_acc = train_correct / len(train_set)
      val_loss /= len(val_loader)
      val_acc = val_correct / len(val_set)

      history['train_loss'].append(train_loss)
      history['val_loss'].append(val_loss)
      history['train_acc'].append(train_acc)
      history['val_acc'].append(val_acc)

      print("-" * 50)
      print(f"Epoch [{epoch+1}/{epcs}]")
      print(f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")
      print(f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")

      # Early stopping
      if val_acc > best_val_acc:
          best_val_acc = val_acc
          patience_counter = 0
          torch.save(model.state_dict(), 'best_model.pth')
      else:
          patience_counter += 1
          if patience_counter >= patience:
              print("Early stopping triggered")
              break

  # Caricamento miglior modello
  model.load_state_dict(torch.load('best_model.pth'))

  # Valutazione su Test
  model.eval()
  test_labels, test_preds, test_probs = [], [], []
  with torch.no_grad():
      for images, tabular, labels in test_loader:
          images, tabular = images.to(device), tabular.to(device)
          outputs = model(images, tabular)
          probs = F.softmax(outputs, dim=1)
          _, preds = torch.max(outputs, 1)
          test_labels.extend(labels.cpu().numpy())
          test_preds.extend(preds.cpu().numpy())
          test_probs.extend(probs.cpu().numpy())

  print("\nTest Classification Report:")
  print(classification_report(test_labels, test_preds, digits=4))

  # Matrice di confusione
  cm = confusion_matrix(test_labels, test_preds)
  plt.figure(figsize=(8,6))
  sns.heatmap(cm, annot=True, fmt='d', xticklabels=[f'Class {i}' for i in range(3)],
              yticklabels=[f'Class {i}' for i in range(3)], cmap='Blues')
  plt.title('Test Confusion Matrix')
  plt.show()

  print("\nMetriche Estese per Classe:")
  # Calcolo sensibilità (recall) e precision
  sensitivity = recall_score(test_labels, test_preds, average=None)
  precision = precision_score(test_labels, test_preds, average=None)

  # Calcolo specificità
  def calculate_specificity(cm):
      specificity = []
      for i in range(cm.shape[0]):
          tn = np.sum(np.delete(np.delete(cm, i, axis=0), i, axis=1))
          fp = np.sum(cm[:, i]) - cm[i, i]
          specificity.append(tn / (tn + fp))
      return specificity

  specificity = calculate_specificity(cm)

  # Stampa risultati
  for i in range(3):
      print(f"Classe {i}:")
      print(f"  - Recall: {sensitivity[i]:.4f}")
      print(f"  - Precision: {precision[i]:.4f}")
      print(f"  - Specificity: {specificity[i]:.4f}")
      print(f"  - F1-score: {2 * (precision[i] * sensitivity[i]) / (precision[i] + sensitivity[i]):.4f}")

  # ROC Curve
  plt.figure(figsize=(8,6))
  y_test_bin = label_binarize(test_labels, classes=[0,1,2])
  for i in range(3):
      fpr, tpr, _ = roc_curve(y_test_bin[:,i], np.array(test_probs)[:,i])
      roc_auc = auc(fpr, tpr)
      plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

  plt.plot([0,1], [0,1], 'k--')
  plt.xlabel('False Positive Rate')
  plt.ylabel('True Positive Rate')
  plt.title('Test ROC Curves')
  plt.legend()
  plt.show()

  # Learning curves
  plt.figure(figsize=(12, 5))
  plt.subplot(1, 2, 1)
  plt.plot(history['train_loss'], label='Train Loss')
  plt.plot(history['val_loss'], label='Validation Loss')
  plt.title('Training and Validation Loss')
  plt.xlabel('Epoch')
  plt.ylabel('Loss')
  plt.legend()

  plt.subplot(1, 2, 2)
  plt.plot(history['train_acc'], label='Train Accuracy')
  plt.plot(history['val_acc'], label='Validation Accuracy')
  plt.title('Training and Validation Accuracy')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend()

  plt.tight_layout()
  plt.show()


  def decrypt_data(encrypted_file, password):
      with open(encrypted_file, 'r') as f:
          encrypted_data = json.load(f)

      # Decodifica i componenti
      salt = base64.b64decode(encrypted_data['salt'])
      nonce = base64.b64decode(encrypted_data['nonce'])
      tag = base64.b64decode(encrypted_data['tag'])
      ciphertext = base64.b64decode(encrypted_data['ciphertext'])

      # Deriva la chiave
      key = PBKDF2(password, salt, 32, count=1000000)

      # Decifra
      cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
      data = cipher.decrypt_and_verify(ciphertext, tag)

      # Converti in dizionario o mantieni come bytes per il modello
      if encrypted_file == 'best_model_encrypted.enc':
          return data  # Restituisci bytes per il modello
      else:
          return json.loads(data.decode('utf-8'))

#Funzione decifratura dei risultati
  def decrypt_and_show_all_results(password):
      """
      Decifra e mostra tutti i risultati dai dati cifrati
      """
      output_dir = "/content/drive/Shareddrives/ProgettoBigData/RisultatiCifrati/"

      try:
          # 1. Decifra e mostra le metriche principali
          print("=" * 50)
          print("RISULTATI DEL MODELLO DECIFRATI")
          print("=" * 50)

          metrics = decrypt_data(os.path.join(output_dir, 'metrics_encrypted.enc'), password)

          # Mostra classification report
          print("\n" + "=" * 50)
          print("CLASSIFICATION REPORT")
          print("=" * 50)

          # Converti il classification report da dizionario a formato testo
          cls_report = metrics['classification_report']
          report_df = pd.DataFrame(cls_report).transpose()
          print(report_df.round(4))

          # Mostra metriche estese per classe
          print("\n" + "=" * 50)
          print("METRICHE ESTESE PER CLASSE")
          print("=" * 50)
          for i in range(3):
              print(f"\nClasse {i}:")
              print(f"  - Recall: {metrics['sensitivity'][i]:.4f}")
              print(f"  - Precision: {metrics['precision'][i]:.4f}")
              print(f"  - Specificity: {metrics['specificity'][i]:.4f}")
              f1 = 2 * (metrics['precision'][i] * metrics['sensitivity'][i]) / (
                          metrics['precision'][i] + metrics['sensitivity'][i])
              print(f"  - F1-score: {f1:.4f}")

          # 2. Decifra e mostra i parametri del modello
          print("\n" + "=" * 50)
          print("PARAMETRI DEL MODELLO")
          print("=" * 50)
          model_params = decrypt_data(os.path.join(output_dir, 'model_params_encrypted.enc'), password)
          for key, value in model_params.items():
              print(f"{key}: {value}")

          # 3. Decifra e mostra informazioni sul dataset
          print("\n" + "=" * 50)
          print("INFORMAZIONI SUL DATASET")
          print("=" * 50)
          dataset_info = decrypt_data(os.path.join(output_dir, 'dataset_info_encrypted.enc'), password)
          print(f"Dimensione training set: {dataset_info['train_size']}")
          print(f"Dimensione validation set: {dataset_info['val_size']}")
          print(f"Dimensione test set: {dataset_info['test_size']}")
          print(f"Feature tabulari: {', '.join(dataset_info['tabular_features'])}")

          # 4. Decifra e mostra le learning curves
          print("\n" + "=" * 50)
          print("CURVE DI APPRENDIMENTO")
          print("=" * 50)
          lc_data = decrypt_data(os.path.join(output_dir, 'learning_curves_data_encrypted.enc'), password)
          print(f"Epoche addestrate: {lc_data['epochs']}")
          print(f"Best validation accuracy: {max(lc_data['val_acc']):.4f}")

          # 5. Decifra e mostra le prestazioni per classe
          print("\n" + "=" * 50)
          print("PRESTAZIONI DETTAGLIATE PER CLASSE")
          print("=" * 50)
          class_perf = decrypt_data(os.path.join(output_dir, 'class_performance_data_encrypted.enc'), password)
          for i in range(3):
              print(f"\nClasse {i}:")
              for metric, value in class_perf[f'class_{i}'].items():
                  print(f"  - {metric}: {value:.4f}")

          # 6. Decifra e mostra le curve ROC
          print("\n" + "=" * 50)
          print("CURVE ROC")
          print("=" * 50)
          roc_data = decrypt_data(os.path.join(output_dir, 'roc_data_encrypted.enc'), password)
          for i in range(3):
              print(f"Classe {i}: AUC = {roc_data[f'class_{i}']['auc']:.4f}")

          # 7. Decifra e mostra la storia dell'addestramento
          print("\n" + "=" * 50)
          print("STORIA ADDESTRAMENTO (ultime 5 epoche)")
          print("=" * 50)
          history_data = decrypt_data(os.path.join(output_dir, 'training_history_encrypted.enc'), password)
          history_df = pd.DataFrame(history_data)
          print(history_df.tail().round(4))

          # 8. Rigenera i grafici
          print("\n" + "=" * 50)
          print("GENERAZIONE GRAFICI...")
          print("=" * 50)

          # Grafico ROC curves
          plt.figure(figsize=(10, 8))
          for i in range(3):
              class_data = roc_data[f'class_{i}']
              plt.plot(class_data['fpr'], class_data['tpr'],
                       label=f'Classe {i} (AUC = {class_data["auc"]:.3f})', linewidth=2)

          plt.plot([0, 1], [0, 1], 'k--', alpha=0.5)
          plt.xlabel('False Positive Rate', fontsize=12)
          plt.ylabel('True Positive Rate', fontsize=12)
          plt.title('Curve ROC - Test Set', fontsize=14)
          plt.legend(fontsize=11)
          plt.grid(True, alpha=0.3)
          plt.show()

          # Grafico Learning curves
          plt.figure(figsize=(15, 5))

          plt.subplot(1, 2, 1)
          plt.plot(lc_data['train_loss'], label='Training Loss', linewidth=2)
          plt.plot(lc_data['val_loss'], label='Validation Loss', linewidth=2)
          plt.xlabel('Epoca', fontsize=12)
          plt.ylabel('Loss', fontsize=12)
          plt.title('Curve di Loss', fontsize=14)
          plt.legend(fontsize=11)
          plt.grid(True, alpha=0.3)

          plt.subplot(1, 2, 2)
          plt.plot(lc_data['train_acc'], label='Training Accuracy', linewidth=2)
          plt.plot(lc_data['val_acc'], label='Validation Accuracy', linewidth=2)
          plt.xlabel('Epoca', fontsize=12)
          plt.ylabel('Accuracy', fontsize=12)
          plt.title('Curve di Accuracy', fontsize=14)
          plt.legend(fontsize=11)
          plt.grid(True, alpha=0.3)

          plt.tight_layout()
          plt.show()

          # Grafico Confusion Matrix
          plt.figure(figsize=(10, 8))
          cm = np.array(metrics['confusion_matrix'])
          sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                      xticklabels=['Classe 0', 'Classe 1', 'Classe 2'],
                      yticklabels=['Classe 0', 'Classe 1', 'Classe 2'])
          plt.title('Matrice di Confusione - Test Set', fontsize=14)
          plt.ylabel('Etichetta Reale', fontsize=12)
          plt.xlabel('Etichetta Predetta', fontsize=12)
          plt.show()

          print("\n" + "=" * 50)
          print("DECIFRAZIONE COMPLETATA CON SUCCESSO!")
          print("=" * 50)

      except Exception as e:
          print(f"Errore durante la decifratura: {str(e)}")
          print("Verifica la password o l'integrità dei file cifrati.")


  # Esegui la decifratura
  if __name__ == "__main__":
      # Richiedi password in modo sicuro
      password = getpass.getpass("Inserisci la password per decifrare i risultati: ")

      decrypt_and_show_all_results(password)

#Funzione cifratura dei risultati
  def encrypt_data(data, password, output_file=None):
      # Converti i dati in JSON e poi in bytes
      if not isinstance(data, (str, bytes)):
          data = json.dumps(data, indent=2)
      if isinstance(data, str):
          data = data.encode('utf-8')

      # Genera un salt randomico
      salt = get_random_bytes(16)

      # Deriva la chiave dalla password usando PBKDF2
      key = PBKDF2(password, salt, 32, count=1000000)

      # Genera un nonce randomico
      nonce = get_random_bytes(12)

      # Crea il cifrario AES-GCM
      cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)

      # Cifra i dati
      ciphertext, tag = cipher.encrypt_and_digest(data)

      # Prepara i dati cifrati
      encrypted_data = {
          'salt': base64.b64encode(salt).decode('utf-8'),
          'nonce': base64.b64encode(nonce).decode('utf-8'),
          'tag': base64.b64encode(tag).decode('utf-8'),
          'ciphertext': base64.b64encode(ciphertext).decode('utf-8')
      }

      # Salva i dati cifrati in un file se specificato
      if output_file:
          with open(output_file, 'w') as f:
              json.dump(encrypted_data, f)
          print(f"Dati cifrati salvati in: {output_file}")

      return encrypted_data

  def encrypt_model(password):

      print("Inizio cifratura del modello...")

      # Directory di output per i file cifrati
      output_dir = "/content/drive/Shareddrives/ProgettoBigData/RisultatiCifrati/"
      os.makedirs(output_dir, exist_ok=True)

      # Cifra il modello addestrato
      print("Cifratura del modello...")
      with open('best_model.pth', 'rb') as f:
          model_data = f.read()
      encrypt_data(model_data, password, os.path.join(output_dir, 'best_model_encrypted.enc'))

      # Elimina il modello in chiaro dopo averlo cifrato
      if os.path.exists('best_model.pth'):
          os.remove('best_model.pth')
          print("Modello in chiaro eliminato.")

  if __name__ == "__main__":
    try:
      # Richiedi password in modo sicuro
      password = getpass.getpass("Inserisci la password per cifrare i risultati: ")
      confirm_password = getpass.getpass("Conferma la password: ")

      if password != confirm_password:
          print("Le password non coincidono!")
          if os.path.exists('best_model.pth'):
                os.remove('best_model.pth')
          exit()

      encrypt_model(password)

    except KeyboardInterrupt:
        print("\nInterruzione durante l'inserimento della password.")
        if os.path.exists('best_model.pth'):
              os.remove('best_model.pth')
        exit()

except KeyboardInterrupt as e:
    print(f"Errore durante l'esecuzione: {str(e)}")
    if os.path.exists('best_model.pth'):
          os.remove('best_model.pth')
          print("Modello eliminato.")