# -*- coding: utf-8 -*-
"""BilanciamentoDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3UV4-PIljIp1IbZmDJAtha-d_OlxZUV
"""

from google.colab import drive
drive.mount('/content/drive')

#Calcolo valori nulli
import os
import pandas as pd
import numpy as np

df=pd.read_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended.csv",sep=";")

# 1. Controllo valori nulli
print("Missing value count (NaN) per column:")
print(df.isna().sum())

# 2. Controllo valori (-inf / inf)
print("\n Invalid (inf / -inf) value count per column:")
print((~np.isfinite(df.select_dtypes(include=[np.number]))).sum())

#Visualizzazione grafici per EDSS, Age e Age of onset e Matrice di correlazione
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df=pd.read_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended.csv",sep=";")

sns.set_style("whitegrid")

df["EDSS"] = df["EDSS"].astype(str).str.replace(",", ".")
df["EDSS"] = pd.to_numeric(df["EDSS"], errors="coerce")

# Plot 1: Age distribution
plt.figure(figsize=(6, 4))
sns.histplot(df["Age"], bins=10, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

# Plot 2: EDSS score distribution
plt.figure(figsize=(6, 4))
sns.histplot(df["EDSS"], bins=10, kde=True)
plt.title("EDSS Score Distribution")
plt.xlabel("EDSS")
plt.ylabel("Frequency")
plt.show()

# Plot 3: Gender count
plt.figure(figsize=(4, 4))
sns.histplot(df['Gender'])
plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

# Plot 4: Age of onset
plt.figure(figsize=(6, 4))
sns.histplot(df["Age of onset"], bins=10, kde=True)
plt.title("Age Of Onset Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

# Plot 5: EDSS vs Age
sns.scatterplot(data=df, x="Age", y="EDSS", hue="Gender")
plt.title("EDSS vs Age")
plt.xlabel("Age")
plt.ylabel("EDSS")
plt.legend(title="Gender")
plt.show()

# Plot 6: EDSS vs Age of onset
plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x="Age of onset", y="EDSS", hue="Gender")
plt.title("EDSS vs Age Of Onset")
plt.xlabel("Age of onset")
plt.ylabel("EDSS")
plt.legend(title="Gender")
plt.show()

# Plot 7: Age vs Age of onset
plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x="Age of onset", y="Age", hue="Gender")
plt.title("Age vs Age Of Onset")
plt.xlabel("Age of onset")
plt.ylabel("Age")
plt.legend(title="Gender")
plt.show()

#Matrice di correlazione e heatmap
df["Disease Duration"] = df["Age"] - df["Age of onset"]

cols = [
    "Age",
    "Age of onset",
    "Disease Duration",
    "EDSS",
    "Pregnancies",
    "Number of Children",
    "Pyramidal",
    "Visual",
    "Motor System",
    "Sensory",
    "Cerebella",
    "Brain stem"
]

for col in cols:
    df[col] = df[col].astype(str).str.replace(",", ".")
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_corr = df[cols].dropna()
corr_matrix = df_corr.corr(method="pearson")

plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlazioni tra variabili cliniche e neurologiche")
plt.tight_layout()
plt.show()

#SHAP
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import shap
import matplotlib.pyplot as plt
import seaborn as sns


# Caricamento dataset
df = pd.read_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended.csv", sep=';')
id_column = df['ID'] if 'ID' in df.columns else pd.Series([None]*len(df))

# Funzione per trasformare EDSS in 3 classi bilanciate
def edss_to_label(edss):
    try:
        edss = str(edss).replace(',', '.')
        edss = float(edss)
        if edss <= 1.5:
            return 0  # Disabilità bassa
        elif edss <= 3.0:
            return 1  # Disabilità moderata
        else:
            return 2  # Disabilità elevata
    except:
        return np.nan

df['EDSS'] = df['EDSS'].apply(edss_to_label)


# Preprocessing
# Salva una copia dell'ID e Gender
df_id_gender = df[['ID', 'Gender']] if 'ID' in df.columns and 'Gender' in df.columns else None

# Rimozione colonne identificative e non utili
columns_to_drop = ['ID', 'First Name', 'Last Name', 'Date of Birth', 'Street Address', 'City',
                   'Country', 'Phone Number', 'Tax Code', 'Email', 'Occupation','Sexual Orientation',
                   'Marital Status','Number of Children','Insurance Coverage']
df.drop(columns=[col for col in columns_to_drop if col in df.columns], inplace=True)

# Codifica variabili categoriche
categorical_cols = df.select_dtypes(include='object').columns.drop('Gender', errors='ignore')
for col in categorical_cols:
    df[col] = df[col].astype(str)
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# Codifica Gender
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].astype(str)
    df['Gender'] = LabelEncoder().fit_transform(df['Gender'])


# Preparazione dati
X = df.drop(columns=['EDSS'])
y = df['EDSS'].astype(int)

# Pulizia nomi colonne
X.columns = X.columns.str.replace(r"[<>[\]]", "", regex=True)
X.columns = X.columns.str.replace(" ", "_")

# Gestione NaN
X = X.fillna(0)

# Addestramento modello
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Performance con tutte le feature:")
print(classification_report(y_test, y_pred))

# Analisi SHAP
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

# Top 20 feature più importanti per ciascuna classe
top_features_by_class = {}

for class_index in range(3):
    mean_abs_shap = np.abs(shap_values.values[:, :, class_index]).mean(axis=0)
    shap_importance = pd.DataFrame({
        'Feature': X.columns,
        'Mean |SHAP value|': mean_abs_shap
    }).sort_values(by='Mean |SHAP value|', ascending=False)

    top_20 = shap_importance.head(20)
    top_features_by_class[class_index] = top_20

    # Visualizzazione grafica per ciascuna classe
    plt.figure(figsize=(10, 6))
    sns.barplot(data=top_20, x='Mean |SHAP value|', y='Feature', hue='Feature', palette='viridis')
    plt.title(f"Top 20 Feature Importance (SHAP) - Classe {class_index}")
    plt.xlabel("Mean |SHAP value|")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.show()

# Selezione ibrida: feature comuni + completamento per impatto
top_n = 10
top_sets = []
for class_idx in range(shap_values.values.shape[2]): #iterazione su ogni classe
    mean_class = np.abs(shap_values.values[:, :, class_idx]).mean(axis=0) #calcolo del valore medio di SHAP su tutte le istanze
    top_class = pd.Series(mean_class, index=X.columns).sort_values(ascending=False).head(top_n) #ordina in modo decrescente e prende le prime 10 feature
    top_sets.append(set(top_class.index)) #inserisce le feature nella lista

common_features = set.intersection(*top_sets) #vengono estratte le feature comuni in tutte le classi
print(f"\n Feature comuni alle Top {top_n} di tutte le classi: {len(common_features)} trovate")
print(sorted(common_features))

mean_abs_global = np.abs(shap_values.values).mean(axis=(0, 2)) #calcolo importanza di tutte le feature
global_importance = pd.Series(mean_abs_global, index=X.columns).sort_values(ascending=False)

ordered_common = [f for f in global_importance.index if f in common_features] #lista con feature comuni
selected_features = ordered_common.copy()
for f in global_importance.index: #scorre tutto il ranking globale
    if f not in selected_features:
        selected_features.append(f) # inserisce le feature non selezionate
    if len(selected_features) == 20:
        break #raggiunte le 20 feature termina l'esecuzione

print(f"\n Feature selezionate per il modello (totale {len(selected_features)}):")
print(selected_features)

# Visualizzazione grafica delle 20 feature selezionate
selected_importance = global_importance[selected_features].sort_values(ascending=False)
selected_df = pd.DataFrame({
    'Feature': selected_importance.index,
    'Mean |SHAP value| (global)': selected_importance.values
})
plt.figure(figsize=(10, 6))
sns.barplot(data=selected_df, x='Mean |SHAP value| (global)', y='Feature', hue='Feature', palette='magma')
plt.title("Top 20 Feature Selezionate SHAP Globale")
plt.xlabel("Mean |SHAP value| (global)")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# Beeswarm e waterfall plot
class_index = 1
shap_values_to_plot = shap_values[:, :, class_index]
shap.plots.beeswarm(shap_values_to_plot, max_display=X.shape[1])

patient_index = 0
shap.plots.waterfall(shap_values[patient_index, :, class_index], max_display=X.shape[1])

# Performance con le feature selezionate
X_shap = X[selected_features]
X_train_shap, X_test_shap, y_train_shap, y_test_shap = train_test_split(X_shap, y, test_size=0.3, random_state=50, stratify=y)

model_shap = RandomForestClassifier(n_estimators=150, random_state=42, class_weight='balanced')
model_shap.fit(X_train_shap, y_train_shap)
y_pred_shap = model_shap.predict(X_test_shap)

print("\n Performance con le feature selezionate dalla strategia ibrida:")
print(classification_report(y_test_shap, y_pred_shap))

# Ricostruisci il dataset finale con le feature selezionate
df_final = X[selected_features].copy()
df_final['EDSS'] = y.values

# Inserisci Gender testuale
if 'Gender' in df.columns:
    gender_map = {0: 'F', 1: 'M', 2: 'N'}
    df_final['Gender'] = df['Gender'].map(gender_map)

# Inserisci ID originale
df_final['ID'] = id_column.values

# Riordina le colonne
cols = df_final.columns.tolist()
ordered_cols = []
if 'ID' in cols: ordered_cols.append('ID')
if 'Gender' in cols: ordered_cols.append('Gender')
if 'EDSS' in cols: ordered_cols.append('EDSS')
ordered_cols += [col for col in cols if col not in ordered_cols]
df_final = df_final[ordered_cols]

# Reset index
df_final.reset_index(drop=True, inplace=True)

# Salvataggio dataset
df_final.to_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info.csv", index=False)

# Visualizzazione grafici per EDSS, Age e Age of onset
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Caricamento dataset
df = pd.read_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info.csv")

# Stile dei grafici
sns.set_style("whitegrid")

# Conversione EDSS in numerico (in caso di virgole decimali)
df["EDSS"] = df["EDSS"].astype(str).str.replace(",", ".")
df["EDSS"] = pd.to_numeric(df["EDSS"], errors="coerce")

# Plot 1: EDSS score distribution
plt.figure(figsize=(6, 4))
sns.histplot(df["EDSS"], bins=10, kde=True)
plt.title("EDSS Score Distribution")
plt.xlabel("EDSS")
plt.ylabel("Frequency")
plt.show()

# Plot 2: EDSS vs Age
plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x="Age", y="EDSS", hue="Gender")
plt.title("EDSS vs Age")
plt.xlabel("Age")
plt.ylabel("EDSS")
plt.legend(title="Gender")
plt.show()

# Plot 3: EDSS vs Age of onset
plt.figure(figsize=(6, 4))
sns.scatterplot(data=df, x="Age_of_onset", y="EDSS", hue="Gender")
plt.title("EDSS vs Age Of Onset")
plt.xlabel("Age of onset")
plt.ylabel("EDSS")
plt.legend(title="Gender")
plt.show()

#Matrice di correlazione e heatmap
df["Disease Duration"] = df["Age"] - df["Age_of_onset"]

cols = [
  "EDSS",
  "Age_of_onset",
  "Age",
  "Pyramidal",
  "Motor_System",
  "Visual",
  "Cerebella",
  "Pregnancies",
  "Disease Duration"
]

for col in cols:
    df[col] = df[col].astype(str).str.replace(",", ".")
    df[col] = pd.to_numeric(df[col], errors='coerce')

df_corr = df[cols].dropna()
corr_matrix = df_corr.corr(method="pearson")

plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlazioni tra variabili cliniche e neurologiche (Pearson)")
plt.tight_layout()
plt.show()