# -*- coding: utf-8 -*-
"""CifraturaDecifratura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XGqkzOubfFTJRtrM47nnV24T4FVVwMU
"""

from google.colab import drive
drive.mount('/content/drive')

#Cifratura Dataset

import pandas as pd
import base64
import json
!pip install pandas pycryptodome
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Protocol.KDF import PBKDF2
import csv
import getpass

def encrypt_dataset(csv_file_path, password, output_file='/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Encrypted.enc'):
    # Leggi il dataset
    df = pd.read_csv(csv_file_path, sep=';')

    # Converti il dataframe in JSON
    data_json = df.to_json(orient='records', indent=2)

    # Prepara i dati per la cifratura
    data = data_json.encode('utf-8')

    # Genera un salt randomico
    salt = get_random_bytes(16)

    # Deriva la chiave dalla password usando PBKDF2
    key = PBKDF2(password, salt, 32, count=1000000)

    # Genera un nonce randomico
    nonce = get_random_bytes(12)

    # Crea il cifrario AES-GCM
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)

    # Cifra i dati
    ciphertext, tag = cipher.encrypt_and_digest(data)

    # Prepara i dati cifrati per il salvataggio
    encrypted_data = {
        'salt': base64.b64encode(salt).decode('utf-8'),
        'nonce': base64.b64encode(nonce).decode('utf-8'),
        'tag': base64.b64encode(tag).decode('utf-8'),
        'ciphertext': base64.b64encode(ciphertext).decode('utf-8')
    }

    # Salva i dati cifrati in un file
    with open(output_file, 'w') as f:
        json.dump(encrypted_data, f)

    print(f"Dataset cifrato salvato in: {output_file}")
    return encrypted_data

if __name__ == "__main__":

    # Richiedi password in modo sicuro
    password = getpass.getpass("Inserisci la password per cifrare: ")
    confirm_password = getpass.getpass("Conferma la password: ")

    if password != confirm_password:
        print("Le password non coincidono!")
        exit()
    input_file = '/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended.csv'
    output_file = '/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Encrypted.enc'

    encrypted_data = encrypt_dataset(input_file, password, output_file)
    print("Cifratura completata con successo!")

#Decifratura Dataset

import pandas as pd
import base64
import json
from Crypto.Cipher import AES
from Crypto.Protocol.KDF import PBKDF2
import csv
from io import StringIO
import getpass

def decrypt_dataset(encrypted_file, password, output_csv='/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Decrypted.csv'):

    # Carica i dati cifrati
    with open(encrypted_file, 'r') as f:
        encrypted_data = json.load(f)

    # Decodifica i componenti
    salt = base64.b64decode(encrypted_data['salt'])
    nonce = base64.b64decode(encrypted_data['nonce'])
    tag = base64.b64decode(encrypted_data['tag'])
    ciphertext = base64.b64decode(encrypted_data['ciphertext'])

    # Deriva la chiave dalla password
    key = PBKDF2(password, salt, 32, count=1000000)

    # Crea il cifrario per decifrare
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)

    # Decifra i dati
    try:
        decrypted_data = cipher.decrypt_and_verify(ciphertext, tag)

        # Converti i dati decifrati in JSON
        data_json = decrypted_data.decode('utf-8')

        # Converti JSON in dataframe usando StringIO
        df = pd.read_json(StringIO(data_json))

        # Salva il dataset decifrato
        df.to_csv(output_csv, sep=';', index=False, quoting=csv.QUOTE_ALL)

        print(f"Dataset decifrato salvato in: {output_csv}")
        return df

    except ValueError:
        print("Errore: Password errata o dati corrotti")
        return None

if __name__ == "__main__":
    # DECIFRATURA
    password = getpass.getpass("Inserisci la password per decifrare: ")
    input_file = '/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Encrypted.enc'
    output_file = '/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Decrypted.csv'

    decrypted_df = decrypt_dataset(input_file, password, output_file)

    if decrypted_df is not None:
        print("Dataset decifrato con successo!")

#SHAP

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import shap
import matplotlib.pyplot as plt
import seaborn as sns


# Caricamento dataset
df = pd.read_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended_Decrypted.csv", sep=';')
id_column = df['ID'] if 'ID' in df.columns else pd.Series([None]*len(df))

# Funzione per trasformare EDSS in 3 classi bilanciate
def edss_to_label(edss):
    try:
        edss = str(edss).replace(',', '.')
        edss = float(edss)
        if edss <= 1.5:
            return 0  # Disabilità bassa
        elif edss <= 3.0:
            return 1  # Disabilità moderata
        else:
            return 2  # Disabilità elevata
    except:
        return np.nan

df['EDSS'] = df['EDSS'].apply(edss_to_label)


# Preprocessing
# Salva una copia dell'ID e Gender
df_id_gender = df[['ID', 'Gender']] if 'ID' in df.columns and 'Gender' in df.columns else None

columns_to_drop = ['ID', 'First Name', 'Last Name', 'Date of Birth', 'Street Address', 'City',
                   'Country', 'Phone Number', 'Tax Code', 'Email', 'Occupation','Sexual Orientation',
                   'Marital Status','Number of Children','Insurance Coverage']
df.drop(columns=[col for col in columns_to_drop if col in df.columns], inplace=True)

# Codifica variabili categoriche
categorical_cols = df.select_dtypes(include='object').columns.drop('Gender', errors='ignore')
for col in categorical_cols:
    df[col] = df[col].astype(str)
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# Codifica Gender
if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].astype(str)
    df['Gender'] = LabelEncoder().fit_transform(df['Gender'])


# Preparazione dati
X = df.drop(columns=['EDSS'])
y = df['EDSS'].astype(int)

# Pulizia nomi colonne
X.columns = X.columns.str.replace(r"[<>[\]]", "", regex=True)
X.columns = X.columns.str.replace(" ", "_")

# Gestione NaN
X = X.fillna(0)

# Addestramento modello
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Performance con tutte le feature:")
print(classification_report(y_test, y_pred))

# Analisi SHAP
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

# Top 20 feature più importanti per ciascuna classe
top_features_by_class = {}

for class_index in range(3):
    mean_abs_shap = np.abs(shap_values.values[:, :, class_index]).mean(axis=0)
    shap_importance = pd.DataFrame({
        'Feature': X.columns,
        'Mean |SHAP value|': mean_abs_shap
    }).sort_values(by='Mean |SHAP value|', ascending=False)

    top_20 = shap_importance.head(20)
    top_features_by_class[class_index] = top_20

    # Visualizzazione grafica per ciascuna classe
    plt.figure(figsize=(10, 6))
    sns.barplot(data=top_20, x='Mean |SHAP value|', y='Feature', hue='Feature', palette='viridis')
    plt.title(f"Top 20 Feature Importance (SHAP) - Classe {class_index}")
    plt.xlabel("Mean |SHAP value|")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.show()

# Selezione ibrida: feature comuni + completamento per impatto
top_n = 10
top_sets = []
for class_idx in range(shap_values.values.shape[2]): #iterazione su ogni classe
    mean_class = np.abs(shap_values.values[:, :, class_idx]).mean(axis=0) #calcolo del valore medio di SHAP su tutte le istanze
    top_class = pd.Series(mean_class, index=X.columns).sort_values(ascending=False).head(top_n) #ordina in modo decrescente e prende le prime 10 feature
    top_sets.append(set(top_class.index)) #inserisce le feature nella lista

common_features = set.intersection(*top_sets) #vengono estratte le feature comuni in tutte le classi
print(f"\n Feature comuni alle Top {top_n} di tutte le classi: {len(common_features)} trovate")
print(sorted(common_features))

mean_abs_global = np.abs(shap_values.values).mean(axis=(0, 2)) #calcolo importanza di tutte le feature
global_importance = pd.Series(mean_abs_global, index=X.columns).sort_values(ascending=False)

ordered_common = [f for f in global_importance.index if f in common_features] #lista con feature comuni
selected_features = ordered_common.copy()
for f in global_importance.index: #scorre tutto il ranking globale
    if f not in selected_features:
        selected_features.append(f) # inserisce le feature non selezionate
    if len(selected_features) == 20:
        break #raggiunte le 20 feature termina l'esecuzione

print(f"\n Feature selezionate per il modello (totale {len(selected_features)}):")
print(selected_features)

# Visualizzazione grafica delle 20 feature selezionate
selected_importance = global_importance[selected_features].sort_values(ascending=False)
selected_df = pd.DataFrame({
    'Feature': selected_importance.index,
    'Mean |SHAP value| (global)': selected_importance.values
})
plt.figure(figsize=(10, 6))
sns.barplot(data=selected_df, x='Mean |SHAP value| (global)', y='Feature', hue='Feature', palette='magma')
plt.title("Top 20 Feature Selezionate SHAP Globale")
plt.xlabel("Mean |SHAP value| (global)")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# Beeswarm e waterfall plot
class_index = 1
shap_values_to_plot = shap_values[:, :, class_index]
shap.plots.beeswarm(shap_values_to_plot, max_display=X.shape[1])

patient_index = 0
shap.plots.waterfall(shap_values[patient_index, :, class_index], max_display=X.shape[1])

# Performance con le feature selezionate
X_shap = X[selected_features]
X_train_shap, X_test_shap, y_train_shap, y_test_shap = train_test_split(X_shap, y, test_size=0.3, random_state=50, stratify=y)

model_shap = RandomForestClassifier(n_estimators=150, random_state=42, class_weight='balanced')
model_shap.fit(X_train_shap, y_train_shap)
y_pred_shap = model_shap.predict(X_test_shap)

print("\n Performance con le feature selezionate dalla strategia ibrida:")
print(classification_report(y_test_shap, y_pred_shap))

# Ricostruisci il dataset finale con le feature selezionate
df_final = X[selected_features].copy()
df_final['EDSS'] = y.values

# Inserisci Gender testuale
if 'Gender' in df.columns:
    gender_map = {0: 'F', 1: 'M', 2: 'N'}
    df_final['Gender'] = df['Gender'].map(gender_map)

# Inserisci ID originale
df_final['ID'] = id_column.values

# Riordina le colonne
cols = df_final.columns.tolist()
ordered_cols = []
if 'ID' in cols: ordered_cols.append('ID')
if 'Gender' in cols: ordered_cols.append('Gender')
if 'EDSS' in cols: ordered_cols.append('EDSS')
ordered_cols += [col for col in cols if col not in ordered_cols]
df_final = df_final[ordered_cols]

# Reset index
df_final.reset_index(drop=True, inplace=True)

# Salvataggio dataset
df_final.to_csv("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Decrypted.csv", index=False)

#Cifratura Immagini
!pip install tenseal
import os
import cv2
import numpy as np
import tenseal as ts
from tqdm import tqdm
import pickle

# Configurazione dei percorsi
input_folder = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices"
output_folder = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices_encrypted"
checkpoint_file = os.path.join(output_folder, "checkpoint.pkl")

# Creazione del contesto TenSEAL per la cifratura CKKS
def create_context():
    context = ts.context(
        ts.SCHEME_TYPE.CKKS, # Schema CKKS per cifratura omomorfica
        poly_modulus_degree=4096,  # Grado del polinomio (impatta sicurezza e performance)
        coeff_mod_bit_sizes=[30, 20, 30] # Imposta lo scale globale per la precisione
    )
    context.generate_galois_keys()
    context.global_scale = 2**20
    return context

# Caricamento, normalizzazione e cifratura di un'immagine
def process_and_encrypt(context, img_path):
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE) # Legge l'immagine in scala di grigi
    img = cv2.resize(img, (64, 64)) # Ridimensiona a 64x64 pixe
    img = cv2.normalize(img, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
    encrypted = ts.ckks_tensor(context, img)  # Cifra l'immagine come tensore CKKS
    return encrypted

# Caricamento dello stato di checkpoint (file già processati)
def load_checkpoint():
    if os.path.exists(checkpoint_file):
        with open(checkpoint_file, "rb") as f:
            return pickle.load(f)
    # Se il checkpoint non esiste, inizializza lo stato
    return {
        'processed_files': set(), # Set di file già cifrati
        'context_saved': False # Flag per sapere se il contesto è già stato salvato
    }

# Salvataggio dello stato di checkpoint
def save_checkpoint(state):
    with open(checkpoint_file, "wb") as f:
        pickle.dump(state, f)

# Funzione principale per cifrare tutte le immagini nella cartella
def encrypt_entire_folder():
    os.makedirs(output_folder, exist_ok=True) # Crea la cartella di output se non esiste
    checkpoint = load_checkpoint() # Carica lo stato precedente

    # Se il contesto non è stato ancora salvato, lo crea e lo salva
    if not checkpoint['context_saved']:
        context = create_context()
        context_path = os.path.join(output_folder, "tenseal_context.seal")
        with open(context_path, "wb") as f:
            f.write(context.serialize(save_secret_key=True))
        checkpoint['context_saved'] = True
        save_checkpoint(checkpoint)
    # Altrimenti lo carica dal file salvato
    else:
        context_path = os.path.join(output_folder, "tenseal_context.seal")
        with open(context_path, "rb") as f:
            context = ts.context_from(f.read())

    # Elenco dei file immagine nella cartella di input
    image_files = [f for f in os.listdir(input_folder)
                 if f.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff'))]

    # Filtra solo i file non ancora processati
    remaining_files = [f for f in image_files if f not in checkpoint['processed_files']]

    # Cifratura dei file rimanenti
    for filename in tqdm(remaining_files, desc="Cifratura immagini mediche"):
        input_path = os.path.join(input_folder, filename)

        # Rinomina sicura del file (evita problemi con virgole)
        safe_filename = filename.replace(",", ".")
        output_path = os.path.join(output_folder, f"{os.path.splitext(safe_filename)[0]}.enc")

        try:
            if not os.path.exists(input_path):
                print(f"File di input non trovato: {input_path}")
                continue

            encrypted_img = process_and_encrypt(context, input_path)

            # Salva il file cifrato
            with open(output_path, "wb") as f:
                f.write(encrypted_img.serialize())

            # Aggiorna il checkpoint
            checkpoint['processed_files'].add(filename)
            save_checkpoint(checkpoint)

        except Exception as e:
            print(f"\nErrore su {filename}: {type(e).__name__} - {str(e)}")
            continue

    if len(remaining_files) == 0:
        print("Tutte le immagini sono già state processate.")
    else:
        print(f"\nCifratura completata. File salvati in: {output_folder}")

if __name__ == "__main__":
    encrypt_entire_folder()

# Decifratura Immagini con Checkpoint
!pip install tenseal
import os
import cv2
import numpy as np
import tenseal as ts
from tqdm import tqdm
import json

# Configurazione
ENCRYPTED_FOLDER = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices_encrypted"
DECRYPTED_FOLDER = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices_decrypted"
CHECKPOINT_FILE = os.path.join(DECRYPTED_FOLDER, "decryption_checkpoint.json")
CONTEXT_PATH = os.path.join(ENCRYPTED_FOLDER, "tenseal_context.seal")

def load_checkpoint():
    if os.path.exists(CHECKPOINT_FILE):
        try:
            with open(CHECKPOINT_FILE, 'r') as f:
                return json.load(f)
        except:
            return {"processed_files": []}
    return {"processed_files": []}

def save_checkpoint(processed_files):
    os.makedirs(DECRYPTED_FOLDER, exist_ok=True)
    with open(CHECKPOINT_FILE, 'w') as f:
        json.dump({"processed_files": processed_files}, f)

def decrypt_all_images():
    # Verifiche preliminari
    if not os.path.exists(CONTEXT_PATH):
        raise FileNotFoundError("Contesto di cifratura non trovato!")

    os.makedirs(DECRYPTED_FOLDER, exist_ok=True)

    # Carica il contesto
    with open(CONTEXT_PATH, "rb") as f:
        context = ts.context_from(f.read())

    # Lista file cifrati
    encrypted_files = [f for f in os.listdir(ENCRYPTED_FOLDER) if f.endswith('.enc')]

    if not encrypted_files:
        print("Nessun file cifrato trovato!")
        return

    # Carica checkpoint
    checkpoint = load_checkpoint()
    processed_files = set(checkpoint["processed_files"])
    files_to_process = [f for f in encrypted_files if f not in processed_files]

    if not files_to_process:
        print("Tutti i file sono già stati processati!")
        return

    print(f"Trovati {len(encrypted_files)} file cifrati. {len(files_to_process)} da processare...")

    success_count = 0
    for filename in tqdm(files_to_process, desc="Decifrazione"):
        try:
            input_path = os.path.join(ENCRYPTED_FOLDER, filename)
            output_path = os.path.join(DECRYPTED_FOLDER, filename.replace('.enc', '.png'))

            # Carica e decifra
            with open(input_path, "rb") as f:
                encrypted = ts.ckks_tensor_from(context, f.read())

            # Conversione esplicita a NumPy
            decrypted = np.array(encrypted.decrypt().tolist())  # Converti prima in lista

            # Normalizzazione e conversione a immagine
            if decrypted.min() < 0 or decrypted.max() > 1:
                decrypted = (decrypted - decrypted.min()) / (decrypted.max() - decrypted.min())

            decrypted = (decrypted * 255).clip(0, 255).astype(np.uint8)

            # Controllo dimensioni
            if decrypted.ndim == 1:
                size = int(np.sqrt(decrypted.shape[0]))
                decrypted = decrypted.reshape((size, size))

            # Salva l'immagine
            cv2.imwrite(output_path, decrypted)
            success_count += 1

            # SALVA CHECKPOINT DOPO OGNI FILE
            processed_files.add(filename)
            save_checkpoint(list(processed_files))

        except Exception as e:
            print(f"\nErrore su {filename}: {type(e).__name__} - {str(e)}")
            continue
        except KeyboardInterrupt:
            print("\nInterruzione rilevata! Checkpoint salvato.")
            save_checkpoint(list(processed_files))
            break

    # Report finale
    print(f"\nDecifrate con successo {success_count}/{len(files_to_process)} immagini")
    if success_count > 0:
        print(f"Immagini salvate in: {DECRYPTED_FOLDER}")

if __name__ == "__main__":
    decrypt_all_images()