# -*- coding: utf-8 -*-
"""EstrazioneSlice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpsV_rDCL1HRkwgEXhlGT2019TDtAu67
"""

from google.colab import drive
drive.mount('/content/drive')

# Disinstallare sympy per evitare conflitti con versioni precedenti
!pip uninstall -y sympy

# Installazione librerie (se necessario)
# Installa torch e torchvision (sympy verrà installato come dipendenza con la versione corretta)
!pip install --upgrade torch torchvision

# La gestione dell'import tramite try/except non è più strettamente necessaria
# dato che stiamo installando le librerie prima dell'import,
# ma la lasciamo per coerenza con il codice originale
import os
import nibabel as nib
import numpy as np
import pandas as pd
from PIL import Image

try:
    import torch
    import torchvision
except ImportError:
    print("Torch e torchvision non trovati, installa con: pip install torch torchvision")

# Definizione delle cartelle
BASE_DIR = "/content/drive/Shareddrives/ProgettoBigData/FotoPazienti"
OUTPUT_DIR = "/content/drive/Shareddrives/ProgettoBigData/dataset_slices"
CSV_FILE = os.path.join("/content/drive/Shareddrives/ProgettoBigData/Patient_Info_Extended.csv")

# Funzione per leggere il dataset e creare il dizionario EDSS
def load_dataset(csv_file):
    df = pd.read_csv(csv_file, header=0, sep=";")
    print("Colonne trovate:", df.columns.tolist())

    edss_dict = dict(zip(df["ID"].astype(int), df["EDSS"]))
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    return edss_dict


# Funzione per estrarre slice dalle immagini MRI
def save_slices(nifti_path, modality, patient_id, edss):
    img = nib.load(nifti_path)
    data = img.get_fdata()

    for i in range(data.shape[2]):
        slice_2d = data[:, :, i]
        slice_norm = 255 * ((slice_2d - np.min(slice_2d)) / (np.ptp(slice_2d)))
        slice_img = Image.fromarray(slice_norm.astype(np.uint8))

        slice_path = os.path.join(OUTPUT_DIR, f"{patient_id}_{modality}_slice{i}_EDSS{edss}.png")
        slice_img.save(slice_path)


# Funzione per processare i pazienti
def process_patients(base_dir, edss_dict):
    for patient_folder in os.listdir(base_dir):
        if not patient_folder.startswith("Patient-"):
            continue

        patient_id = patient_folder.split("-")[-1]
        if not patient_id.isdigit():
            continue

        patient_id = int(patient_id)
        edss = edss_dict.get(patient_id)

        if edss is None:
            print(f"EDSS non trovato per paziente {patient_id}")
            continue

        patient_path = os.path.join(base_dir, patient_folder)

        for file in os.listdir(patient_path):
            if "LesionSeg" in file:  # Ignoriamo le immagini segmentate
                continue
            if file.endswith(".nii") and ("Flair" in file or "T1" in file or "T2" in file):
                modality = "Flair" if "Flair" in file else "T1" if "T1" in file else "T2"

                full_path = os.path.join(patient_path, file)
                save_slices(full_path, modality, patient_id, edss)

# Funzione principale di avvio
def main():
    edss_dict = load_dataset(CSV_FILE)
    process_patients(BASE_DIR, edss_dict)


if __name__ == "__main__":
    main()